/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ClinicsComponent {
    }
}
declare global {
    interface HTMLClinicsComponentElement extends Components.ClinicsComponent, HTMLStencilElement {
    }
    var HTMLClinicsComponentElement: {
        prototype: HTMLClinicsComponentElement;
        new (): HTMLClinicsComponentElement;
    };
    interface HTMLElementTagNameMap {
        "clinics-component": HTMLClinicsComponentElement;
    }
}
declare namespace LocalJSX {
    interface ClinicsComponent {
    }
    interface IntrinsicElements {
        "clinics-component": ClinicsComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "clinics-component": LocalJSX.ClinicsComponent & JSXBase.HTMLAttributes<HTMLClinicsComponentElement>;
        }
    }
}
