/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ClinicsComponent {
    }
    interface TableComponent {
    }
    interface TestTable {
        "properties": any;
    }
}
declare global {
    interface HTMLClinicsComponentElement extends Components.ClinicsComponent, HTMLStencilElement {
    }
    var HTMLClinicsComponentElement: {
        prototype: HTMLClinicsComponentElement;
        new (): HTMLClinicsComponentElement;
    };
    interface HTMLTableComponentElement extends Components.TableComponent, HTMLStencilElement {
    }
    var HTMLTableComponentElement: {
        prototype: HTMLTableComponentElement;
        new (): HTMLTableComponentElement;
    };
    interface HTMLTestTableElement extends Components.TestTable, HTMLStencilElement {
    }
    var HTMLTestTableElement: {
        prototype: HTMLTestTableElement;
        new (): HTMLTestTableElement;
    };
    interface HTMLElementTagNameMap {
        "clinics-component": HTMLClinicsComponentElement;
        "table-component": HTMLTableComponentElement;
        "test-table": HTMLTestTableElement;
    }
}
declare namespace LocalJSX {
    interface ClinicsComponent {
    }
    interface TableComponent {
    }
    interface TestTable {
        "properties"?: any;
    }
    interface IntrinsicElements {
        "clinics-component": ClinicsComponent;
        "table-component": TableComponent;
        "test-table": TestTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "clinics-component": LocalJSX.ClinicsComponent & JSXBase.HTMLAttributes<HTMLClinicsComponentElement>;
            "table-component": LocalJSX.TableComponent & JSXBase.HTMLAttributes<HTMLTableComponentElement>;
            "test-table": LocalJSX.TestTable & JSXBase.HTMLAttributes<HTMLTestTableElement>;
        }
    }
}
